using System;

namespace TheForest.Buildings.Creation
{
	public enum BuildingTypes
	{
		None,
		Cage = 10,
		EffigyHead = 20,
		EffigyLarge = 30,
		EffigyRain = 40,
		EffigySmall = 50,
		EffigyEx = 55,
		Fire = 60,
		FireParallel = 63,
		FireReflector = 66,
		FireRockPit = 70,
		FireStand = 80,
		Roof,
		RoofOLD = 79,
		Floor = 82,
		Stairs,
		Dock,
		Foundation,
		FloorHole = 87,
		RaftEx,
		RaftOarEx,
		Garden,
		GardenEx,
		UndergroundGardenEx,
		Coaster,
		HouseBoat = 100,
		LeafShelter = 110,
		LogCabin = 120,
		LogCabinMed = 130,
		LogHolder = 140,
		LogHolderLarge,
		LogSled = 150,
		Platform = 160,
		RockSidePlatform,
		PlatformBridge,
		TreePlatform = 165,
		TreePlatformAnchor,
		Raft = 170,
		RockHolder = 180,
		RockHolderLarge,
		Shelter = 190,
		Staircase = 200,
		ClimbingRope = 205,
		StickHolder = 210,
		StickHolderLarge,
		StickMarker = 220,
		TempShelter = 225,
		TrapDeadfall = 230,
		TrapPole = 235,
		TrapRope = 240,
		TrapSimple = 245,
		TrapSpikedWall = 250,
		TrapSwingingRock,
		TreeHouse = 260,
		TreeHouseAnchor,
		Wall = 270,
		WallEx,
		WallExH = 275,
		WallSmall,
		StickFence = 272,
		RockFence,
		BoneFence,
		WallDefensive = 280,
		WallDefensiveReinforcement,
		WallDefensiveGate,
		WallDoorway = 290,
		WallWindow = 300,
		WorkBench = 310,
		ItemStash = 315,
		WeaponRack,
		ArmorMannequin,
		DryingRack = 320,
		DryingRackLite,
		BonFire = 330,
		TreeHouseChatel = 340,
		TreeHouseChatelAnchor,
		Walkway = 349,
		RockPathEx,
		RabbitTrap = 360,
		FishTrap = 365,
		Gazeebo = 370,
		DefensiveSpikes = 380,
		MedicineCabinet = 390,
		ExplosiveHolder = 400,
		ArrowBasket = 402,
		BoneBasket = 404,
		SnackHolder = 410,
		SkinRack = 415,
		TrapTripWireExplosive = 420,
		TrapTripWireMolotov,
		TrapLeafPile = 425,
		SkullLight = 430,
		CeilingSkullLight,
		Bed = 440,
		Table = 443,
		TableSmall,
		Chair = 446,
		BoneChair,
		Couch,
		Target = 450,
		SideTable = 460,
		FirePlace = 470,
		WallItemCache = 500,
		FloorItemCache,
		WaterCollector = 600,
		TreeSapCollector = 610,
		Birdhouse = 620,
		Decoration_deerSkin = 2000,
		Decoration_rabbitSkin,
		Decoration_skull = 2100,
		Decoration_Trophy = 2200,
		Decoration_WallWeaponHolder = 2300,
		Decoration_GroundWeaponHolder = 2310,
		Decoration_WallPlantPot = 2400,
		Decoration_BoneChandelier = 2410,
		Decoration_BoneFrame = 2420,
		Decoration_StickFrame,
		Decoration_RabbitWallRug = 2430,
		RockThrower = 2500,
		Crane = 3001,
		Zipline,
		ZiplineTree,
		Swap_AnimalTrap = 5000,
		Swap_Floor = 5010,
		Swap_Platform = 5020,
		Swap_WeaponHolderDecoration = 5030,
		TimmyEffigy = 7001,
		TimmyEffigySitting,
		MomEffigy,
		MomEffigySitting,
		TVeffigy,
		Dogeffigy,
		CarEffigy,
		Signal = 8000,
		Church = 9000,
		Coffin,
		HangGlider,
		Wardrobe,
		Cross,
		Tower
	}
}
